remote_theme: just-the-docs/just-the-docs

title: 캡스톤디자인_34조
description: 캡스톤 디자인 34조 프로젝트 페이지
baseurl: ""
url: "https://kookmin-sw.github.io/capstone-2024-34"
search_enabled: false

footer_content: "Copyright &copy; 2024 Kookmin Univ. All rights reserved."
